### ISSUE TITLE
Development environment on localhost?

### ISSUE THREAD

**Issue by LoRosset** [capnmidnight/Calla#102]
Hi!

Thank you for your work on Calla, it is really nice ! :-)

I tried to install Calla as it is written in the README file, with Docker. Everything seems to run as it should but I only have the jitsi interface that come up. I used the local IP adress (localhost) as a host.

Do you have an idea of why this is happening ?

The folder "Calla" is under the config folder of jitsi. My .env file is as follow (only the parts that I have touched, otherwise it is the default environment as in the example file). Note that I am on Ubuntu 20.04.1 LTS:
# .env
   HTTP_PORT=8000
   HTTPS_PORT=8443
   PUBLIC_URL=https://localhost
   DOCKER_HOST_ADDRESS=https://localhost
   ENABLE_HTTP_REDIRECT=1

Here is what I wrote in the docker-compose.yml file : 

# Calla
    calla:
        image: nginx:alpine
        restart: ${RESTART_POLICY}
        volumes:
              - ${CONFIG}/Calla/js:/usr/share/nginx/html
        command: sh /usr/share/nginx/html/entrypoint.sh
        environment:
             - JITSI_HOST=localhost
             - JVB_HOST=jvb.meet.jitsi
             - JVB_MUC=muc.jvb.meet.jitsi

**EDIT:**
I've seen that I did something wrong regarding the ${CONF} directory! I'll try again setting this up correctly. But I don't get any files in there even when launching the command _docker-compose up -d_

Ok, so I've correctly set up the ${CONF} directory now (it was created under /root/ which I didn't notice. I changed it to my local directory). However I still can't see the Calla website (when accessing localhost:8443 or localhost or even jitsi.localhost or meet.jitsi.localhost). On jitsi.localhost and meet.jitsi.localhost I end up on the "Welcome to nginx!" page.

**Comment by LoRosset** [comment]
The folder "js" which is created inside the Calla folder under ${CONFIG}, when launching docker-compose, is also empty

**Comment by LoRosset** [comment]
I've manage to make it work with the answer here #95

**Comment by Gulianrdgd** [comment]
Wait @LoRosset, did you manage to get it working with the current repo? Or did you use the old repo?
I'm currently trying to set it up myself but it is not working....

**Comment by LoRosset** [comment]
I used the old repository ! 👍
