### ISSUE TITLE
how this project share the position of the users

### ISSUE THREAD

**Issue by manang** [capnmidnight/Calla#105]
Hi,
Can you tell me how this application share the position of the users?
does it use the data channel of webrtc?

Do you have a chart about this thing?
Thank you very much
angelo

**Comment by capnmidnight** [comment]
Position sharing is performed through Jitsi's inter-user messaging system. Yes, this is ultimately a WebRTC dataChannel. It's done this way to minimize the need for any server resources specific to Calla.

The way the repository looks like Calla right now makes it look like Calla requires a server backend. I had been experimenting learning ASP.NET Core at the time and used SignalR to implement a text chat feature. But this isn't strictly required. I'll be removing that very soon. 

I use Calla in one of my projects at work and had left the public Calla repo alone while I worked out some issues with going from Calla's original 2D audio field to full 3D support. I'll be merging those changes in very soon.
