### ISSUE TITLE
Basic example not working properly

### ISSUE THREAD

**Issue by enricol96** [capnmidnight/Calla#108]
Hello,
I'm trying to use the basic example (https://www.calla.chat/basic/) but if I open multiple tabs the users' rectangle movements have a wrong vertical displacement: if I click on a point in the map, the rectangle moves but it's not centered with respect to the mouse cursor (on the contrary, it's below it). The higher the number of opened tabs the larger the top offset.

Instead, if I open just one tab and I'm the first user joining the room everything is fine.
Any idea on how to fix it?
Thanks

**Comment by enricol96** [comment]
I solved the problem and submitted a pull request (#109), it may be useful for others facing the same issue.

**Comment by capnmidnight** [comment]
Thanks for the PR. It's merged now.
