### ISSUE TITLE
dynamic import lib-jitsi-meet

### ISSUE THREAD

**Issue by manang** [capnmidnight/Calla#112]
Hi, can you tell me why you need to import dynamically lib-jitsi-meet?
Thanks

**Comment by capnmidnight** [comment]
This is a limitation of Jitsi Meet. Versions of `lib-jitsi-meet` are tied to versions of the Jitsi Meet installation to which you are connecting. The Jitsi dev team doesn't provide a module-based version of `lib-jitsi-meet`. So they claim the safest thing is to always dynamically load `lib-jitsi-meet` from your Jitsi Meet server.

It's annoying. I don't agree with their reasoning. I have some other issues with Jitsi: https://github.com/capnmidnight/Calla/issues/103
