### ISSUE TITLE
Give room admin option to change map

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Calla#21]
Let the room admin select an existing map for the room. There should be some default, and then the first user in the room can change it, and then subsequent users get the latest room from the admin.

**Comment by capnmidnight** [comment]
Could use the room subject line for this

**Comment by emilkarolak** [comment]
Hi,
could you please give some info on logic of room changing? 
I tried to implement doors and simultaneous changing room & map (so you don't see ppl from previous room on the new map). 
Adding doors and events to them was quite easy, but I have big problem in room changing logics - I tried dozens of approaches but none worked like it should. I have most issues with other users - either you can't see others present in new room or they cant hear you or have no avatar, or are doubled etc. I tried full-api approach, i tried opposite - so just delegating events to actions you already provided - but none works perfectly - room change happens, but afterwards not everything works as expected even if I just emulate click on buttons "Leave" and "Connect"

My current (non-fully-working) approach is something like [called in init.js on room change event]:
`               //leave current room
                await client.leaveAsync();
                game.end(false);
                directory.clear();
                game.users = new Map();
                login.connecting = false;
                login.connected = false;
                login.ready = true;
                //enter new room
                client = new LibJitsiMeetClient(JITSI_HOST, JVB_HOST, JVB_MUC);
                hide(login, 'none !important');
                settings.roomName = login.roomName = evt.roomName;
                let tirggerClick = document.createEvent('HTMLEvents');
                tirggerClick.initEvent('click', true, false);
                document.body.querySelector("#connect").dispatchEvent(tirggerClick);`

Can I have some help? You have deep understanding of what you've done so maybe you can think of something I'm doing wrong here?

**Comment by capnmidnight** [comment]
archiving
