### ISSUE TITLE
Using video feeds for user avatars

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Calla#39]
After Issue #33, implement video feeds as user avatars

**Comment by mooomooo** [comment]
Perhaps a project like https://github.com/t-mullen/video-stream-merger may be helpful, especially if doing something like #40, to use the audio positioning math to similarly position (and scale) the appropriate line of sight video streams into a single FPS video.

**Comment by capnmidnight** [comment]
This is available on the live site now. It's off by default, as I still don't think it's all that much of an improvement over Emoji avatar. Open the options and enable video from there to see the effect.
