### ISSUE TITLE
Add search to emoji picker

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Calla#42]

**Comment by mooomooo** [comment]
If you don't mind including others' code, there's this vanilla js emoji picker library : https://github.com/joeattardi/emoji-button

**Comment by capnmidnight** [comment]
I'm torn. Let me work through some file-size math.

My own emoji code is 166KB of the 994KB minified bundle[0]. Wow, I didn't realize just how much space the emoji were taking up (17%)! My own code is only 243KB of that bundle, the rest is lib-jitsi-meet (667KB) and jquery (88KB) (which is required by lib-jitsi-meet).  (the numbers don't add up quite right, I guess the minifier must strip some stuff out of lib-jitsi-meet or jquery).

emoji-button's minified code is 234KB, an additional 68KB. So that would leave the final build size around 1062KB, a 6.8% increase to the total app bundle size, for a total of 22% of the app bundle. 

Actually, I did the math assuming I wanted to change to bundling lib-jits-meet statically (it's currently loaded with a dynamic import), but now that I see the numbers, I want to work to keep the app bundle small so that it loads quickly and we get to usable interaction sooner. The "login" button is disabled until the initial app bundle downloads and sets it to enabled. By dynamically loading lib-jitsi-meet and jquery, we get the user to the point of proving engagement much, much earlier. So with that in mind, an additional 68KB would be a 28% increase in the app bundle size, making the emoji code a full 75% of the app bundle (whereas it's currently 68%).

I think I'd rather stick to my own code and pair the number of emoji used in the project down to a more usable set. I think I have a chance to compress my emoji definitions more by loop-constructing the skin-tone variations. Also, the EmojiForm matches the design of the rest of the options forms. Not that it's a great design, but the design is configured in one place, so they could all be upgraded together.

**Comment by capnmidnight** [comment]
Got the total bundle size down to 142KB, of which the emoji is now about 50% of.

**Comment by capnmidnight** [comment]
archiving
