### ISSUE TITLE
Potential audio optimizations

### ISSUE THREAD

**Issue by patcon** [capnmidnight/Calla#43]
Love this project!

Seems there may be ways to tweak the noise cancellation features of Jitsi Meet that are causing issue: https://community.jitsi.org/t/higher-audio-quality/31441/6

Have any of these been attempted yet?

**Comment by capnmidnight** [comment]
Interesting

Here is the code in lib-jitsi-meet where the values are read https://github.com/jitsi/lib-jitsi-meet/blob/dffe94f270f692c7421412bbbc597279e4a2d805/modules/RTC/RTCUtils.js#L77-L90

Gives a little more explanation for what they do.

Seems like you can achieve turning them all off with just setting "disableAP" (disables all audio processing) to true.

I've turned them off, but I don't have a good way to test it and see how it sounds.

**Comment by capnmidnight** [comment]
User "aseeg" says he was unable to tell a difference after testing, with any setting other than enabling stereo audio. But that also doubles the bandwidth usage. I don't know, this sounds pretty dubious.

**Comment by patcon** [comment]
Ah, ok! Thanks! Looking through all the sub-settings, really surprised there's no effect. I suppose we could close this?

Hm. Or maybe the final check might be to confirm these findings as matching expectations of Jitsi dev's?

Also, tracing back the constraints object, seems like it might be per-user:
https://github.com/jitsi/lib-jitsi-meet/blob/dffe94f270f692c7421412bbbc597279e4a2d805/modules/RTC/RTCUtils.js#L1367

This jibes with another thread I saw, where someone was running a dance party, and only the person playing the music was supposed to toggle those settings...

Think this is worth keeping open and experimenting more, or should we close?

**Comment by patcon** [comment]
Hey Sean, if I were to describe this to Jitsi devs, with just enough information to help them evaluate/diagnose a potential solution, how would you describe how Calla works? (I understand it to be that sound volume is adjusted at browser level, but the server still sees it as a regular full-volume conference of however many ppl are in the map?)

**Comment by capnmidnight** [comment]
Yes, the server software is unmodified. There is a small amount of code manually injected into the Jitsi Meet web client that listens for messages from the Calla client (there is no Calla server, all user sync messages are routed through Jitsi Meet). The injected code receives commands to find and reroute the audio element's MediaStream through the WebAudio API to apply a PannerNode, which performs the spatialization.

With spatialized audio, you actually want monaural audio sources, but switching to stereo and down-mixing in the WebAudio API might improve the sampling rate, IDK.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by capnmidnight** [comment]
I'm currently using what they call the "External API", which runs the standard web client in an IFrame on your page. I'm in the process of converting to either lib-jitsi-meet, or just writing my own WebRTC client code (assuming most of their magic is in the server software, accessed via TURN).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by capnmidnight** [comment]
Calla now uses lib-jitsi-meet.

**Comment by mooomooo** [comment]
Does this mean the jitsi-hax is no longer necessary?

**Comment by capnmidnight** [comment]
That is correct. Calla now works with the full, default, unmodified install of Jitsi Meet.

**Comment by capnmidnight** [comment]
Oh, also, the spatialization is now done through [Resonance Audio](https://resonance-audio.github.io/resonance-audio/develop/web/getting-started.html), rather than [PannerNode](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode). Quality is significantly better. PannerNode had a lot of crackling it induced in the audio stream.

**Comment by mooomooo** [comment]
Using lib-jitsi-meet necessitated some changes when using docker; PR #52 addresses those.  Ideally nothing should have changed for when not using docker.

**Comment by capnmidnight** [comment]
using LibJitsiMeet gives us greater control over some features like echo cancellation and such, though it might require writing a hax wrapper around `RTCPeerConnection`.
