### ISSUE TITLE
Easier (docker) install

### ISSUE THREAD

**Issue by mooomooo** [capnmidnight/Calla#46]
If you could consider default URLs of jitsi.<domain> and calla.<domain> (and maybe redirect www. to calla. if you wanted to keep that?), then PR #45 makes it so that you don't need to edit any files when hosting on other domains.

**Comment by capnmidnight** [comment]
I'll be merging your PR shortly. The current status is that jitsihax.js is required, but now that issue #33 is complete, after issue #48 is fixed, and some testing and a few small additions to the audio interface, Calla will be completely self-contained. I think I will still run the front-end and back-ends from different domains, but eventually jitsihax.js will go away completely.
