### ISSUE TITLE
"Leave" button doesn't actually leave chat

### ISSUE THREAD

**Issue by mooomooo** [capnmidnight/Calla#51]
It drops the UI back to the main screen, but the jitsi remains connected in the background.

**Comment by capnmidnight** [comment]
I've seen this same issue as well. `BaseJitsiClient` might not be waiting for the `videoConferenceLeft` correctly. Or `ExternalJitsiClient` or `LibJitsiClient` might not be calling the right paths to end the session.

Was this in the live site (which currently uses `ExternalJitsiClient`)? Or was this in one of the test pages?

**Comment by mooomooo** [comment]
This was on the main site.

**Comment by capnmidnight** [comment]
This should be fixed now

**Comment by mooomooo** [comment]
It does appear to successfully leave the room, but the mic / camera seem to remain active?  On my computer at least, it continues to consume CPU as well.

**Comment by capnmidnight** [comment]
Ah, I think that we be fairly easy to address. Just need to remove all the local tracks before leaving. Will also need to shut down the "audio client", which is the thing that manages the spatialization.

**Comment by capnmidnight** [comment]
Okay, leaving now disconnects the mic and camera

**Comment by mooomooo** [comment]
Looks good.  It does leave behind the on-screen widgets, but they are successfully deactivated so that's just aesthetic.

Is there a particular reason why joining a room redraws the main page rather than taking you to a new page?  With a new page, leaving becomes cleaner, and you also get the ability to directly link to a room similar to how jitsi lets you connect to a specific chat.

**Comment by capnmidnight** [comment]
Technically, joining a room is a separate step from logging into the Jitsi instance. Eventually, I want to let people walk around on a map to choose their room. Navigating between pages will break that.

Also, the current room gets added as a hash in the URL, so you can actually link people to your room in Calla. Just copy and paste the current URL. There's also a button in the headerbar for tweeting out a link to your current room.
