### ISSUE TITLE
Create online map editor tool

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Calla#77]
Maps should be editable. Room admins should be able to select rooms (which is already tracked in Issue #21). Maps should be savable to the server.

**Comment by patcon** [comment]
Or could use the high fidelity approach of just pointing to an external image map :)
https://map.highfidelity.com/DfFq8zih057Z3qe3/?map=https%3A%2F%2Fi.imgur.com%2FtqdiQ5Y.png

**Comment by chr5tphr** [comment]
Actually, I really like the idea of creating environments on the fly. I kind of thought about this after a virtual conference, but it would be awesome if you could put down like a sign that's essentially a poster people can look at while you explain it to them. Or a video that is like the shared youtube view of jitsi, only pinned to a location so people who are interested can gather around.

**Comment by patcon** [comment]
> Actually, I really like the idea of creating environments on the fly.

Yeah! and people can make simple maps that help with "breakout group" formats (on the same map or spinning out into others). custom maps are essentially a huge extensibility layer where lots of emergent styles of engagement can emerge :) Someone could literally make a whole separate service that helps people generate these custom maps together using motifs and patterns, so an unconference event could allow people to select from a buffet of breakout styles, or people could together build their own and run workshops/events on them :)

Also, alpha layer of PNGs could be height data -- MVP could be just binary walkable/barrier, but later could allow walking up gradients/ramps, but basically any jump of more than X many units of luminosity could act as a barrier.

**Comment by capnmidnight** [comment]
I used the Tiled Map Editor to make the current map (https://thorbjorn.itch.io/tiled).

There is an interesting issue with the current implementation of Calla. There's no "backend server", i.e. everything goes through Jitsi. Jitsi provides a WebRTC dataChannel between users that, with some minor effort, I can use as a basic serialization pipe for data between users.

Editable maps would, at first blush, seem to require a central server for storing the data. But maybe there is something interesting that could be done with consensus algorithms.

**Comment by capnmidnight** [comment]
archiving
