### ISSUE TITLE
Create whiteboarding tool

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Calla#82]
Similar to Issue #81, create a room area that can be used as a shared drawing space. Maybe each user draws on a different image layer, and images are blended together.

**Comment by chrysn** [comment]
A pattern I've seen somewhat successfully used in gather.town is placing "items" in rooms that pop up to be iframes. Those can be static content (paintings on walls, announcements of events, link lists to further information), but can also be interactive elements that are loaded with a particular room identifier of their choosing.

Thus, a whiteboard would be relatively easy to add by just linking to a collaborative editing tool, be it an Etherpad or a drawing board.
