### ISSUE TITLE
Game view not available?

### ISSUE THREAD

**Issue by bitcloudTheFirst** [capnmidnight/Calla#97]
Hi, I don't know if I'm missing something here, but I can see the basic view, and this works fine, but I can't seem to find or implement the game view.

I have tried duplicating the basic view html file and replacing with game.js. I've also tried going through every error and adding in appropriate div ids etc, and I've asked my developer to look at this as well and he also can't see where to find, or how to build the other views?

Can you advise? Thanks

**Comment by capnmidnight** [comment]
This isn't so much a bug report as a cry for help. I can't do anything for you without a bug report. 

https://www.softwaretestinghelp.com/how-to-write-good-bug-report
