### ISSUE TITLE
Possibility to use other mapping systems?

### ISSUE THREAD

**Issue by askvictor** [capnmidnight/Calla#98]
The specific use-case I'm thinking about is using this together with Minecraft (Education Edition, but not reason couldn't be used in other versions); as users get closer to each other in-game, they can hear each other. It's relatively easy to get a set of co-ordinates for users in a Minecraft world using websocket commands; if there were an API in Calla where I could send the usernames + co-ordinates, that might just work; also such an API would allow other games to be used.

**Comment by capnmidnight** [comment]
Calla runs in the browser, not on a server. It uses Jitsi inter-user messaging system to transmit state between users. There's no server backend, so there's nowhere to put an API endpoint.

You could, however, make your own thing using Calla that did have an API endpoint. Unfortunately, I'm too busy with my day job to be able to write anything about how that would work. However, perhaps the basic setup tutorial might give you some ideas: https://github.com/capnmidnight/Calla/blob/master/Calla/doc/basic/Tutorial.md
